# Generated by Django 5.1.6 on 2025-02-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Course", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="course",
            table="course",
        ),
    ]
