# Generated by Django 5.1.6 on 2025-02-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Questionnaire", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="questionnaire",
            table="questionnaire",
        ),
    ]
